import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
<<<<<<< HEAD
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
=======
>>>>>>> b53af87 (Initial commit from Create Next App)
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Nexa CRM | Precision Deal Management",
  description: "The modern CRM for teams who value speed, design, and absolute clarity.",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> b53af87 (Initial commit from Create Next App)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en" className="dark" style={{ colorScheme: "dark" }}>
        <body className={`${geistSans.variable} ${geistMono.variable} bg-black font-sans antialiased`}>
          {children}
        </body>
      </html>
    </ClerkProvider>
=======
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
>>>>>>> b53af87 (Initial commit from Create Next App)
  );
}
